# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1086, 543)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\src\\logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.update_pushButton = QtWidgets.QPushButton(Form)
        self.update_pushButton.setGeometry(QtCore.QRect(60, 460, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.update_pushButton.setPalette(palette)
        self.update_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update_pushButton.setMouseTracking(False)
        self.update_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(85, 170, 0);  /* Final background */\n"
"    border: 4px solid rgb(255, 170, 0);  /* Visible border */\n"
"    font: 100 18pt \"MS Serif\";\n"
"    border-radius: 14px;\n"
"    \n"
"    border-color: rgb(0, 79, 0,200);\n"
"    padding: 6px;\n"
"}\n"
"\n"
"")
        self.update_pushButton.setFlat(False)
        self.update_pushButton.setObjectName("update_pushButton")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(21, 100, 251, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet("font: 16pt \"Tempus Sans ITC\";\n"
"font: 75 16pt \"Verdana\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("font: 16pt \"Tempus Sans ITC\";\n"
"font: 75 16pt \"Verdana\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.a_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.a_lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(85, 255, 0);\n"
"    border: 2px solid rgb(255, 198, 65);\n"
"    font: 57 16pt \"Yu Gothic Medium\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.a_lineEdit.setObjectName("a_lineEdit")
        self.gridLayout.addWidget(self.a_lineEdit, 1, 1, 1, 1)
        self.b_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.b_lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(85, 255, 0);\n"
"    border: 2px solid rgb(255, 198, 65);\n"
"    font: 57 16pt \"Yu Gothic Medium\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.b_lineEdit.setObjectName("b_lineEdit")
        self.gridLayout.addWidget(self.b_lineEdit, 2, 1, 1, 1)
        self.gamma_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.gamma_lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(85, 255, 0);\n"
"    border: 2px solid rgb(255, 198, 65);\n"
"    font: 57 16pt \"Yu Gothic Medium\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.gamma_lineEdit.setObjectName("gamma_lineEdit")
        self.gridLayout.addWidget(self.gamma_lineEdit, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("font: 16pt \"Tempus Sans ITC\";\n"
"font: 75 16pt \"Verdana\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(320, 30, 721, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plottingSpace_verticallayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plottingSpace_verticallayout.setContentsMargins(0, 0, 0, 0)
        self.plottingSpace_verticallayout.setObjectName("plottingSpace_verticallayout")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 290, 222, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setStyleSheet("font: 16pt \"Tempus Sans ITC\";\n"
"font: 75 16pt \"Verdana\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setStyleSheet("font: 16pt \"Tempus Sans ITC\";\n"
"font: 75 16pt \"Verdana\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gammaA_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gammaA_lineEdit.setStyleSheet("QLineEdit {\n"
"   \n"
"    background-color: rgb(85, 255, 255);\n"
"    border: 2px solid rgb(255, 198, 65);\n"
"    font: 57 16pt \"Yu Gothic Medium\";\n"
"    qproperty-alignment: AlignCenter;\n"
"    border-color: rgb(85, 85, 255);\n"
"}\n"
"")
        self.gammaA_lineEdit.setText("")
        self.gammaA_lineEdit.setObjectName("gammaA_lineEdit")
        self.gridLayout_2.addWidget(self.gammaA_lineEdit, 1, 1, 1, 1)
        self.gammaB_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gammaB_lineEdit.setStyleSheet("QLineEdit {\n"
"   \n"
"    background-color: rgb(85, 255, 255);\n"
"    border: 2px solid rgb(255, 198, 65);\n"
"    font: 57 16pt \"Yu Gothic Medium\";\n"
"    qproperty-alignment: AlignCenter;\n"
"    border-color: rgb(85, 85, 255);\n"
"}\n"
"")
        self.gammaB_lineEdit.setText("")
        self.gammaB_lineEdit.setObjectName("gammaB_lineEdit")
        self.gridLayout_2.addWidget(self.gammaB_lineEdit, 2, 1, 1, 1)
        self.gammaY_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gammaY_lineEdit.setStyleSheet("QLineEdit {\n"
"   \n"
"    background-color: rgb(85, 255, 255);\n"
"    border: 2px solid rgb(255, 198, 65);\n"
"    font: 57 16pt \"Yu Gothic Medium\";\n"
"    qproperty-alignment: AlignCenter;\n"
"    border-color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        self.gammaY_lineEdit.setText("")
        self.gammaY_lineEdit.setObjectName("gammaY_lineEdit")
        self.gridLayout_2.addWidget(self.gammaY_lineEdit, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setStyleSheet("font: 16pt \"Tempus Sans ITC\";\n"
"font: 75 16pt \"Verdana\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(60, 30, 161, 51))
        self.label_7.setStyleSheet("font: 16pt \"Tempus Sans ITC\";\n"
"\n"
"font: 75 22pt \"Candara\";")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "2D-BZ Viewer (by aymen mahmoudi)"))
        self.update_pushButton.setText(_translate("Form", "Update BZ"))
        self.label.setText(_translate("Form", "b"))
        self.label_2.setText(_translate("Form", "a"))
        self.a_lineEdit.setText(_translate("Form", "5"))
        self.b_lineEdit.setText(_translate("Form", "3.4"))
        self.gamma_lineEdit.setText(_translate("Form", "90"))
        self.label_3.setText(_translate("Form", "angle"))
        self.label_4.setText(_translate("Form", "|Γ–B|"))
        self.label_5.setText(_translate("Form", "|Γ–A|"))
        self.label_6.setText(_translate("Form", "|Γ–Y|"))
        self.label_7.setText(_translate("Form", "2D-BZ Viewer"))
